// Generated by PicoPixel.io — https://picopixel.io
#ifndef PICOPIXEL_LVGL_UI_EVENTS_H
#define PICOPIXEL_LVGL_UI_EVENTS_H

#include "lvgl.h"

#ifdef __cplusplus
extern "C" {
#endif

void button_1_clicked_cb(lv_event_t * e);
void button_2_clicked_cb(lv_event_t * e);
void button_3_clicked_cb(lv_event_t * e);
void button_4_clicked_cb(lv_event_t * e);
void pp_anim_stop_timelines_for_deleted_tree(lv_obj_t * root);

#ifdef __cplusplus
}
#endif

#endif /*PICOPIXEL_LVGL_UI_EVENTS_H*/
