// Generated by PicoPixel.io — https://picopixel.io
#include "actions.h"
#include "screens.h"
#include "ui.h"

// Animation timeline helpers
void pp_anim_stop_timelines_for_deleted_tree(lv_obj_t * root) {
    (void)root;
}


// Event callback implementations

// Event callback for button_1 on clicked
void button_1_clicked_cb(lv_event_t * e) {
    lv_scr_load_anim(objects.screen_2, LV_SCR_LOAD_ANIM_MOVE_LEFT, 5000, 0, false);
}


// Event callback for button_2 on clicked
void button_2_clicked_cb(lv_event_t * e) {
    lv_scr_load_anim(objects.screen_3, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, false);
}


// Event callback for button_3 on clicked
void button_3_clicked_cb(lv_event_t * e) {
    lv_scr_load_anim(objects.screen_1, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, false);
}


// Event callback for button_4 on clicked
void button_4_clicked_cb(lv_event_t * e) {
    lv_scr_load_anim(objects.screen_1, LV_SCR_LOAD_ANIM_MOVE_LEFT, 5000, 0, false);
}

