idf_component_register(
    SRCS
        "ui.c"
        "screens.c"
        "clock_screen.c"
        "battery_screen.c"
        "notification_screen.c"
        "statusbar.c"
        "actions.c"
        "vars.c"
        "images.c"
        "styles.c"
        "fonts/fonts.c"
        "fonts/lv_font_montserrat_14_ext.c"
        "fonts/lv_font_montserrat_16_ext.c"
        "fonts/lv_font_montserrat_72_ext.c"
        "fonts/lv_font_montserrat_164.c"
        "fonts/lv_font_shoe_print_48.c"
    INCLUDE_DIRS 
        "." 
        "fonts" 
        "${CMAKE_SOURCE_DIR}/main/tasks"
    REQUIRES lvgl
)
