// Generated by PicoPixel.io — https://picopixel.io
#include <string.h>

#include "screens.h"
#include "images.h"
#include "fonts/fonts.h"
#include "actions.h"
#include "vars.h"
#include "styles.h"
#include "ui.h"

objects_t objects;
lv_obj_t *tick_value_change_obj;
uint32_t active_theme_index = 0;

void create_screen_screen_1() {
    lv_obj_t *obj = lv_obj_create(0);
    objects.screen_1 = obj;
    lv_obj_set_pos(obj, 0, 0);
    lv_obj_set_size(obj, 410, 502);
    {
        lv_obj_t *parent_obj = obj;
        {
            // button_1
            lv_obj_t *obj = lv_btn_create(parent_obj);
            objects.button_1 = obj;
            lv_obj_set_pos(obj, 316, 210);
            lv_obj_set_size(obj, 63, 59);
            lv_obj_set_style_border_side(obj, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_transform_pivot_x(obj, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_transform_pivot_y(obj, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_border_color(obj, lv_color_hex(0xff000000), LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_border_width(obj, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
            {
                lv_obj_t *parent_obj = obj;
                {
                    // button_1_label
                    lv_obj_t *obj = lv_label_create(parent_obj);
                    objects.button_1_label = obj;
                    lv_label_set_text(obj, "Next");
                    lv_obj_center(obj);
                }
            }
        }
        {
            // button_2
            lv_obj_t *obj = lv_btn_create(parent_obj);
            objects.button_2 = obj;
            lv_obj_set_pos(obj, 35, 211);
            lv_obj_set_size(obj, 63, 59);
            lv_obj_set_style_border_side(obj, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_transform_pivot_x(obj, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_transform_pivot_y(obj, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_border_color(obj, lv_color_hex(0xff000000), LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_border_width(obj, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
            {
                lv_obj_t *parent_obj = obj;
                {
                    // button_2_label
                    lv_obj_t *obj = lv_label_create(parent_obj);
                    objects.button_2_label = obj;
                    lv_label_set_text(obj, "Back");
                    lv_obj_center(obj);
                }
            }
        }
    }

    // Event callback registrations
    lv_obj_add_flag(objects.button_1, LV_OBJ_FLAG_CLICKABLE);
    lv_obj_add_event_cb(objects.button_1, button_1_clicked_cb, LV_EVENT_CLICKED, NULL);
    lv_obj_add_flag(objects.button_2, LV_OBJ_FLAG_CLICKABLE);
    lv_obj_add_event_cb(objects.button_2, button_2_clicked_cb, LV_EVENT_CLICKED, NULL);

    tick_screen_screen_1();
}

void tick_screen_screen_1() {
}


void create_screen_screen_3() {
    lv_obj_t *obj = lv_obj_create(0);
    objects.screen_3 = obj;
    lv_obj_set_pos(obj, 0, 0);
    lv_obj_set_size(obj, 410, 502);
    {
        lv_obj_t *parent_obj = obj;
        {
            // button_4
            lv_obj_t *obj = lv_btn_create(parent_obj);
            objects.button_4 = obj;
            lv_obj_set_pos(obj, 330, 209);
            lv_obj_set_size(obj, 63, 59);
            lv_obj_set_style_border_side(obj, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_transform_pivot_x(obj, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_transform_pivot_y(obj, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_border_color(obj, lv_color_hex(0xff000000), LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_border_width(obj, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
            {
                lv_obj_t *parent_obj = obj;
                {
                    // button_4_label
                    lv_obj_t *obj = lv_label_create(parent_obj);
                    objects.button_4_label = obj;
                    lv_label_set_text(obj, "Next");
                    lv_obj_center(obj);
                }
            }
        }
    }

    // Event callback registrations
    lv_obj_add_flag(objects.button_4, LV_OBJ_FLAG_CLICKABLE);
    lv_obj_add_event_cb(objects.button_4, button_4_clicked_cb, LV_EVENT_CLICKED, NULL);

    tick_screen_screen_3();
}

void tick_screen_screen_3() {
}


void create_screen_screen_2() {
    lv_obj_t *obj = lv_obj_create(0);
    objects.screen_2 = obj;
    lv_obj_set_pos(obj, 0, 0);
    lv_obj_set_size(obj, 410, 502);
    {
        lv_obj_t *parent_obj = obj;
        {
            // slider_1
            lv_obj_t *obj = lv_slider_create(parent_obj);
            objects.slider_1 = obj;
            lv_obj_set_pos(obj, 153, 230);
            lv_obj_set_size(obj, 200, 20);
            lv_slider_set_range(obj, 0, 100);
            lv_slider_set_value(obj, 50, LV_ANIM_OFF);
        }
        {
            // button_3
            lv_obj_t *obj = lv_btn_create(parent_obj);
            objects.button_3 = obj;
            lv_obj_set_pos(obj, 24, 210);
            lv_obj_set_size(obj, 63, 59);
            lv_obj_set_style_border_side(obj, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_transform_pivot_x(obj, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_transform_pivot_y(obj, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_border_color(obj, lv_color_hex(0xff000000), LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_border_width(obj, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
            {
                lv_obj_t *parent_obj = obj;
                {
                    // button_3_label
                    lv_obj_t *obj = lv_label_create(parent_obj);
                    objects.button_3_label = obj;
                    lv_label_set_text(obj, "Back");
                    lv_obj_center(obj);
                }
            }
        }
    }

    // Event callback registrations
    lv_obj_add_flag(objects.button_3, LV_OBJ_FLAG_CLICKABLE);
    lv_obj_add_event_cb(objects.button_3, button_3_clicked_cb, LV_EVENT_CLICKED, NULL);

    tick_screen_screen_2();
}

void tick_screen_screen_2() {
}



typedef void (*tick_screen_func_t)();
tick_screen_func_t tick_screen_funcs[] = {
    tick_screen_screen_1,
    tick_screen_screen_3,
    tick_screen_screen_2,
};
void tick_screen(int screen_index) {
    tick_screen_funcs[screen_index]();
}
void tick_screen_by_id(enum ScreensEnum screenId) {
    tick_screen_funcs[screenId - 1]();
}

void delete_screen_screen_1() {
    if (objects.screen_1 != NULL) {
        pp_anim_stop_timelines_for_deleted_tree(objects.screen_1);
        lv_obj_del(objects.screen_1);
    }
    objects.screen_1 = 0;
    objects.button_1 = 0;
    objects.button_1_label = 0;
    objects.button_2 = 0;
    objects.button_2_label = 0;
}

void delete_screen_screen_3() {
    if (objects.screen_3 != NULL) {
        pp_anim_stop_timelines_for_deleted_tree(objects.screen_3);
        lv_obj_del(objects.screen_3);
    }
    objects.screen_3 = 0;
    objects.button_4 = 0;
    objects.button_4_label = 0;
}

void delete_screen_screen_2() {
    if (objects.screen_2 != NULL) {
        pp_anim_stop_timelines_for_deleted_tree(objects.screen_2);
        lv_obj_del(objects.screen_2);
    }
    objects.screen_2 = 0;
    objects.slider_1 = 0;
    objects.button_3 = 0;
    objects.button_3_label = 0;
}


typedef void (*delete_screen_func_t)();
delete_screen_func_t delete_screen_funcs[] = {
    delete_screen_screen_1,
    delete_screen_screen_3,
    delete_screen_screen_2,
};
void delete_screen_by_id(enum ScreensEnum screenId) {
    delete_screen_funcs[screenId - 1]();
}

void create_screens() {
    lv_disp_t *dispp = lv_disp_get_default();
    // Use dark theme (true) to match the editor's appearance - white text on dark buttons
    lv_theme_t *theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED), true, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);

    create_screen_screen_1();
    create_screen_screen_3();
    create_screen_screen_2();
}
