// Generated by PicoPixel.io — https://picopixel.io
#ifndef PICOPIXEL_LVGL_UI_SCREENS_H
#define PICOPIXEL_LVGL_UI_SCREENS_H

#include "lvgl.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef struct _objects_t {
    lv_obj_t *screen_1;
    lv_obj_t *screen_3;
    lv_obj_t *screen_2;
    lv_obj_t *button_1;
    lv_obj_t *slider_1;
    lv_obj_t *button_2;
    lv_obj_t *button_3;
    lv_obj_t *button_4;
    lv_obj_t *button_1_label;
    lv_obj_t *button_2_label;
    lv_obj_t *button_3_label;
    lv_obj_t *button_4_label;
} objects_t;

extern objects_t objects;

enum ScreensEnum {
    SCREEN_ID_SCREEN_1 = 1,
    SCREEN_ID_SCREEN_3 = 2,
    SCREEN_ID_SCREEN_2 = 3,
};

void create_screen_screen_1();
void tick_screen_screen_1();
void delete_screen_screen_1();
void create_screen_screen_3();
void tick_screen_screen_3();
void delete_screen_screen_3();
void create_screen_screen_2();
void tick_screen_screen_2();
void delete_screen_screen_2();

void tick_screen_by_id(enum ScreensEnum screenId);
void tick_screen(int screen_index);

void delete_screen_by_id(enum ScreensEnum screenId);

void create_screens();


#ifdef __cplusplus
}
#endif

#endif /*PICOPIXEL_LVGL_UI_SCREENS_H*/
