// Generated by PicoPixel.io — https://picopixel.io
#ifndef PICOPIXEL_LVGL_UI_STYLES_H
#define PICOPIXEL_LVGL_UI_STYLES_H

#include "lvgl.h"

#ifdef __cplusplus
extern "C" {
#endif



#ifdef __cplusplus
}
#endif

#endif /*PICOPIXEL_LVGL_UI_STYLES_H*/
