// Generated by PicoPixel.io — https://picopixel.io
#include "vars.h"

typedef struct {
    const char *name;
    uint8_t type; // 0=int32, 1=string, 2=float, 3=bool
} native_var_t;

const native_var_t native_vars[] = {};

const uint32_t native_vars_count = 0;

