// Generated by PicoPixel.io — https://picopixel.io
#ifndef PICOPIXEL_LVGL_UI_FONTS_H
#define PICOPIXEL_LVGL_UI_FONTS_H

#include "lvgl.h"

#ifdef __cplusplus
extern "C" {
#endif

// Custom fonts with full Latin-1 (0x20-0xFF) — includes ä ö ü Ä Ö Ü ß
LV_FONT_DECLARE(lv_font_montserrat_14_ext);
LV_FONT_DECLARE(lv_font_montserrat_16_ext);
LV_FONT_DECLARE(lv_font_montserrat_72_ext);
LV_FONT_DECLARE(lv_font_montserrat_164);
LV_FONT_DECLARE(lv_font_shoe_print_48);

/* Get a custom font by name, returns NULL if not found */
const lv_font_t* ui_get_font_by_name(const char* name);

#ifdef __cplusplus
}
#endif

#endif /*PICOPIXEL_LVGL_UI_FONTS_H*/
