// Generated by PicoPixel.io — https://picopixel.io
/**
 * @file fonts.c
 * @brief Custom font lookup for LVGL UI
 *
 * Each font .c file is compiled separately.
 */

#include "fonts.h"
#include <string.h>

const lv_font_t* ui_get_font_by_name(const char* name) {
    if (name == NULL) return NULL;
    /* No custom fonts */
    return NULL;
}
